<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert(['id' => 1101, 'province_id' => 11, 'name' => 'Kab. Aceh Selatan']);
        DB::table('cities')->insert(['id' => 1102, 'province_id' => 11, 'name' => 'Kab. Aceh Tenggara']);
        DB::table('cities')->insert(['id' => 1103, 'province_id' => 11, 'name' => 'Kab. Aceh Timur']);
        DB::table('cities')->insert(['id' => 1104, 'province_id' => 11, 'name' => 'Kab. Aceh Tengah']);
        DB::table('cities')->insert(['id' => 1105, 'province_id' => 11, 'name' => 'Kab. Aceh Barat']);
        DB::table('cities')->insert(['id' => 1106, 'province_id' => 11, 'name' => 'Kab. Aceh Besar']);
        DB::table('cities')->insert(['id' => 1107, 'province_id' => 11, 'name' => 'Kab. Pidie']);
        DB::table('cities')->insert(['id' => 1108, 'province_id' => 11, 'name' => 'Kab. Aceh Utara']);
        DB::table('cities')->insert(['id' => 1109, 'province_id' => 11, 'name' => 'Kab. Simeulue']);
        DB::table('cities')->insert(['id' => 1110, 'province_id' => 11, 'name' => 'Kab. Aceh Singkil']);
        DB::table('cities')->insert(['id' => 1111, 'province_id' => 11, 'name' => 'Kab. Bireuen']);
        DB::table('cities')->insert(['id' => 1112, 'province_id' => 11, 'name' => 'Kab. Aceh Barat Daya']);
        DB::table('cities')->insert(['id' => 1113, 'province_id' => 11, 'name' => 'Kab. Gayo Lues']);
        DB::table('cities')->insert(['id' => 1114, 'province_id' => 11, 'name' => 'Kab. Aceh Jaya']);
        DB::table('cities')->insert(['id' => 1115, 'province_id' => 11, 'name' => 'Kab. Nagan Raya']);
        DB::table('cities')->insert(['id' => 1116, 'province_id' => 11, 'name' => 'Kab. Aceh Tamiang']);
        DB::table('cities')->insert(['id' => 1117, 'province_id' => 11, 'name' => 'Kab. Bener Meriah']);
        DB::table('cities')->insert(['id' => 1118, 'province_id' => 11, 'name' => 'Kab. Pidie Jaya']);
        DB::table('cities')->insert(['id' => 1171, 'province_id' => 11, 'name' => 'Kota Banda Aceh']);
        DB::table('cities')->insert(['id' => 1172, 'province_id' => 11, 'name' => 'Kota Sabang']);
        DB::table('cities')->insert(['id' => 1173, 'province_id' => 11, 'name' => 'Kota Lhokseumawe']);
        DB::table('cities')->insert(['id' => 1174, 'province_id' => 11, 'name' => 'Kota Langsa']);
        DB::table('cities')->insert(['id' => 1175, 'province_id' => 11, 'name' => 'Kota Subulussalam']);
        DB::table('cities')->insert(['id' => 1201, 'province_id' => 12, 'name' => 'Kab. Tapanuli Tengah']);
        DB::table('cities')->insert(['id' => 1202, 'province_id' => 12, 'name' => 'Kab. Tapanuli Utara']);
        DB::table('cities')->insert(['id' => 1203, 'province_id' => 12, 'name' => 'Kab. Tapanuli Selatan']);
        DB::table('cities')->insert(['id' => 1204, 'province_id' => 12, 'name' => 'Kab. Nias']);
        DB::table('cities')->insert(['id' => 1205, 'province_id' => 12, 'name' => 'Kab. Langkat']);
        DB::table('cities')->insert(['id' => 1206, 'province_id' => 12, 'name' => 'Kab. Karo']);
        DB::table('cities')->insert(['id' => 1207, 'province_id' => 12, 'name' => 'Kab. Deli Serdang']);
        DB::table('cities')->insert(['id' => 1208, 'province_id' => 12, 'name' => 'Kab. Simalungun']);
        DB::table('cities')->insert(['id' => 1209, 'province_id' => 12, 'name' => 'Kab. Asahan']);
        DB::table('cities')->insert(['id' => 1210, 'province_id' => 12, 'name' => 'Kab. Labuhanbatu']);
        DB::table('cities')->insert(['id' => 1211, 'province_id' => 12, 'name' => 'Kab. Dairi']);
        DB::table('cities')->insert(['id' => 1212, 'province_id' => 12, 'name' => 'Kab. Toba Samosir']);
        DB::table('cities')->insert(['id' => 1213, 'province_id' => 12, 'name' => 'Kab. Mandailing Natal']);
        DB::table('cities')->insert(['id' => 1214, 'province_id' => 12, 'name' => 'Kab. Nias Selatan']);
        DB::table('cities')->insert(['id' => 1215, 'province_id' => 12, 'name' => 'Kab. Pakpak Bharat']);
        DB::table('cities')->insert(['id' => 1216, 'province_id' => 12, 'name' => 'Kab. Humbang Hasundutan']);
        DB::table('cities')->insert(['id' => 1217, 'province_id' => 12, 'name' => 'Kab. Samosir']);
        DB::table('cities')->insert(['id' => 1218, 'province_id' => 12, 'name' => 'Kab. Serdang Bedagai']);
        DB::table('cities')->insert(['id' => 1219, 'province_id' => 12, 'name' => 'Kab. Batu Bara']);
        DB::table('cities')->insert(['id' => 1220, 'province_id' => 12, 'name' => 'Kab. Padang Lawas Utara']);
        DB::table('cities')->insert(['id' => 1221, 'province_id' => 12, 'name' => 'Kab. Padang Lawas']);
        DB::table('cities')->insert(['id' => 1222, 'province_id' => 12, 'name' => 'Kab. Labuhanbatu Selatan']);
        DB::table('cities')->insert(['id' => 1223, 'province_id' => 12, 'name' => 'Kab. Labuhanbatu Utara']);
        DB::table('cities')->insert(['id' => 1224, 'province_id' => 12, 'name' => 'Kab. Nias Utara']);
        DB::table('cities')->insert(['id' => 1225, 'province_id' => 12, 'name' => 'Kab. Nias Barat']);
        DB::table('cities')->insert(['id' => 1271, 'province_id' => 12, 'name' => 'Kota Medan']);
        DB::table('cities')->insert(['id' => 1272, 'province_id' => 12, 'name' => 'Kota Pematang Siantar']);
        DB::table('cities')->insert(['id' => 1273, 'province_id' => 12, 'name' => 'Kota Sibolga']);
        DB::table('cities')->insert(['id' => 1274, 'province_id' => 12, 'name' => 'Kota Tanjung Balai']);
        DB::table('cities')->insert(['id' => 1275, 'province_id' => 12, 'name' => 'Kota Binjai']);
        DB::table('cities')->insert(['id' => 1276, 'province_id' => 12, 'name' => 'Kota Tebing Tinggi']);
        DB::table('cities')->insert(['id' => 1277, 'province_id' => 12, 'name' => 'Kota Padangsidimpuan']);
        DB::table('cities')->insert(['id' => 1278, 'province_id' => 12, 'name' => 'Kota Gunungsitoli']);
        DB::table('cities')->insert(['id' => 1301, 'province_id' => 13, 'name' => 'Kab. Pesisir Selatan']);
        DB::table('cities')->insert(['id' => 1302, 'province_id' => 13, 'name' => 'Kab. Solok']);
        DB::table('cities')->insert(['id' => 1303, 'province_id' => 13, 'name' => 'Kab. Sijunjung']);
        DB::table('cities')->insert(['id' => 1304, 'province_id' => 13, 'name' => 'Kab. Tanah Datar']);
        DB::table('cities')->insert(['id' => 1305, 'province_id' => 13, 'name' => 'Kab. Padang Pariaman']);
        DB::table('cities')->insert(['id' => 1306, 'province_id' => 13, 'name' => 'Kab. Agam']);
        DB::table('cities')->insert(['id' => 1307, 'province_id' => 13, 'name' => 'Kab. Lima Puluh Kota']);
        DB::table('cities')->insert(['id' => 1308, 'province_id' => 13, 'name' => 'Kab. Pasaman']);
        DB::table('cities')->insert(['id' => 1309, 'province_id' => 13, 'name' => 'Kab. Kepulauan Mentawai']);
        DB::table('cities')->insert(['id' => 1310, 'province_id' => 13, 'name' => 'Kab. Dharmasraya']);
        DB::table('cities')->insert(['id' => 1311, 'province_id' => 13, 'name' => 'Kab. Solok Selatan']);
        DB::table('cities')->insert(['id' => 1312, 'province_id' => 13, 'name' => 'Kab. Pasaman Barat']);
        DB::table('cities')->insert(['id' => 1371, 'province_id' => 13, 'name' => 'Kota Padang']);
        DB::table('cities')->insert(['id' => 1372, 'province_id' => 13, 'name' => 'Kota Solok']);
        DB::table('cities')->insert(['id' => 1373, 'province_id' => 13, 'name' => 'Kota Sawahlunto']);
        DB::table('cities')->insert(['id' => 1374, 'province_id' => 13, 'name' => 'Kota Padang Panjang']);
        DB::table('cities')->insert(['id' => 1375, 'province_id' => 13, 'name' => 'Kota Bukittinggi']);
        DB::table('cities')->insert(['id' => 1376, 'province_id' => 13, 'name' => 'Kota Payakumbuh']);
        DB::table('cities')->insert(['id' => 1377, 'province_id' => 13, 'name' => 'Kota Pariaman']);
        DB::table('cities')->insert(['id' => 1401, 'province_id' => 14, 'name' => 'Kab. Kampar']);
        DB::table('cities')->insert(['id' => 1402, 'province_id' => 14, 'name' => 'Kab. Indragiri Hulu']);
        DB::table('cities')->insert(['id' => 1403, 'province_id' => 14, 'name' => 'Kab. Bengkalis']);
        DB::table('cities')->insert(['id' => 1404, 'province_id' => 14, 'name' => 'Kab. Indragiri Hilir']);
        DB::table('cities')->insert(['id' => 1405, 'province_id' => 14, 'name' => 'Kab. Pelalawan']);
        DB::table('cities')->insert(['id' => 1406, 'province_id' => 14, 'name' => 'Kab. Rokan Hulu']);
        DB::table('cities')->insert(['id' => 1407, 'province_id' => 14, 'name' => 'Kab. Rokan Hilir']);
        DB::table('cities')->insert(['id' => 1408, 'province_id' => 14, 'name' => 'Kab. Siak']);
        DB::table('cities')->insert(['id' => 1409, 'province_id' => 14, 'name' => 'Kab. Kuantan Singingi']);
        DB::table('cities')->insert(['id' => 1410, 'province_id' => 14, 'name' => 'Kab. Kepulauan Meranti']);
        DB::table('cities')->insert(['id' => 1471, 'province_id' => 14, 'name' => 'Kota Pekanbaru']);
        DB::table('cities')->insert(['id' => 1472, 'province_id' => 14, 'name' => 'Kota Dumai']);
        DB::table('cities')->insert(['id' => 1501, 'province_id' => 15, 'name' => 'Kab. Kerinci']);
        DB::table('cities')->insert(['id' => 1502, 'province_id' => 15, 'name' => 'Kab. Merangin']);
        DB::table('cities')->insert(['id' => 1503, 'province_id' => 15, 'name' => 'Kab. Sarolangun']);
        DB::table('cities')->insert(['id' => 1504, 'province_id' => 15, 'name' => 'Kab. Batanghari']);
        DB::table('cities')->insert(['id' => 1505, 'province_id' => 15, 'name' => 'Kab. Muaro Jambi']);
        DB::table('cities')->insert(['id' => 1506, 'province_id' => 15, 'name' => 'Kab. Tanjung Jabung Barat']);
        DB::table('cities')->insert(['id' => 1507, 'province_id' => 15, 'name' => 'Kab. Tanjung Jabung Timur']);
        DB::table('cities')->insert(['id' => 1508, 'province_id' => 15, 'name' => 'Kab. Bungo']);
        DB::table('cities')->insert(['id' => 1509, 'province_id' => 15, 'name' => 'Kab. Tebo']);
        DB::table('cities')->insert(['id' => 1571, 'province_id' => 15, 'name' => 'Kota Jambi']);
        DB::table('cities')->insert(['id' => 1572, 'province_id' => 15, 'name' => 'Kota Sungai Penuh']);
        DB::table('cities')->insert(['id' => 1601, 'province_id' => 16, 'name' => 'Kab. Ogan Komering Ulu']);
        DB::table('cities')->insert(['id' => 1602, 'province_id' => 16, 'name' => 'Kab. Ogan Komering Ilir']);
        DB::table('cities')->insert(['id' => 1603, 'province_id' => 16, 'name' => 'Kab. Muara Enim']);
        DB::table('cities')->insert(['id' => 1604, 'province_id' => 16, 'name' => 'Kab. Lahat']);
        DB::table('cities')->insert(['id' => 1605, 'province_id' => 16, 'name' => 'Kab. Musi Rawas']);
        DB::table('cities')->insert(['id' => 1606, 'province_id' => 16, 'name' => 'Kab. Musi Banyuasin']);
        DB::table('cities')->insert(['id' => 1607, 'province_id' => 16, 'name' => 'Kab. Banyuasin']);
        DB::table('cities')->insert(['id' => 1608, 'province_id' => 16, 'name' => 'Kab. Ogan Komering Ulu Timur']);
        DB::table('cities')->insert(['id' => 1609, 'province_id' => 16, 'name' => 'Kab. Ogan Komering Ulu Selatan']);
        DB::table('cities')->insert(['id' => 1610, 'province_id' => 16, 'name' => 'Kab. Ogan Ilir']);
        DB::table('cities')->insert(['id' => 1611, 'province_id' => 16, 'name' => 'Kab. Empat Lawang']);
        DB::table('cities')->insert(['id' => 1612, 'province_id' => 16, 'name' => 'Kab. Penukal Abab Lematang Ilir']);
        DB::table('cities')->insert(['id' => 1613, 'province_id' => 16, 'name' => 'Kab. Musi Rawas Utara']);
        DB::table('cities')->insert(['id' => 1671, 'province_id' => 16, 'name' => 'Kota Palembang']);
        DB::table('cities')->insert(['id' => 1672, 'province_id' => 16, 'name' => 'Kota Pagar Alam']);
        DB::table('cities')->insert(['id' => 1673, 'province_id' => 16, 'name' => 'Kota Lubuk Linggau']);
        DB::table('cities')->insert(['id' => 1674, 'province_id' => 16, 'name' => 'Kota Prabumulih']);
        DB::table('cities')->insert(['id' => 1701, 'province_id' => 17, 'name' => 'Kab. Bengkulu Selatan']);
        DB::table('cities')->insert(['id' => 1702, 'province_id' => 17, 'name' => 'Kab. Rejang Lebong']);
        DB::table('cities')->insert(['id' => 1703, 'province_id' => 17, 'name' => 'Kab. Bengkulu Utara']);
        DB::table('cities')->insert(['id' => 1704, 'province_id' => 17, 'name' => 'Kab. Kaur']);
        DB::table('cities')->insert(['id' => 1705, 'province_id' => 17, 'name' => 'Kab. Seluma']);
        DB::table('cities')->insert(['id' => 1706, 'province_id' => 17, 'name' => 'Kab. Muko Muko']);
        DB::table('cities')->insert(['id' => 1707, 'province_id' => 17, 'name' => 'Kab. Lebong']);
        DB::table('cities')->insert(['id' => 1708, 'province_id' => 17, 'name' => 'Kab. Kepahiang']);
        DB::table('cities')->insert(['id' => 1709, 'province_id' => 17, 'name' => 'Kab. Bengkulu Tengah']);
        DB::table('cities')->insert(['id' => 1771, 'province_id' => 17, 'name' => 'Kota Bengkulu']);
        DB::table('cities')->insert(['id' => 1801, 'province_id' => 18, 'name' => 'Kab. Lampung Selatan']);
        DB::table('cities')->insert(['id' => 1802, 'province_id' => 18, 'name' => 'Kab. Lampung Tengah']);
        DB::table('cities')->insert(['id' => 1803, 'province_id' => 18, 'name' => 'Kab. Lampung Utara']);
        DB::table('cities')->insert(['id' => 1804, 'province_id' => 18, 'name' => 'Kab. Lampung Barat']);
        DB::table('cities')->insert(['id' => 1805, 'province_id' => 18, 'name' => 'Kab. Tulang Bawang']);
        DB::table('cities')->insert(['id' => 1806, 'province_id' => 18, 'name' => 'Kab. Tanggamus']);
        DB::table('cities')->insert(['id' => 1807, 'province_id' => 18, 'name' => 'Kab. Lampung Timur']);
        DB::table('cities')->insert(['id' => 1808, 'province_id' => 18, 'name' => 'Kab. Way Kanan']);
        DB::table('cities')->insert(['id' => 1809, 'province_id' => 18, 'name' => 'Kab. Pesawaran']);
        DB::table('cities')->insert(['id' => 1810, 'province_id' => 18, 'name' => 'Kab. Pringsewu']);
        DB::table('cities')->insert(['id' => 1811, 'province_id' => 18, 'name' => 'Kab. Mesuji']);
        DB::table('cities')->insert(['id' => 1812, 'province_id' => 18, 'name' => 'Kab. Tulang Bawang Barat']);
        DB::table('cities')->insert(['id' => 1813, 'province_id' => 18, 'name' => 'Kab. Pesisir Barat']);
        DB::table('cities')->insert(['id' => 1871, 'province_id' => 18, 'name' => 'Kota Bandar Lampung']);
        DB::table('cities')->insert(['id' => 1872, 'province_id' => 18, 'name' => 'Kota Metro']);
        DB::table('cities')->insert(['id' => 1901, 'province_id' => 19, 'name' => 'Kab. Bangka']);
        DB::table('cities')->insert(['id' => 1902, 'province_id' => 19, 'name' => 'Kab. Belitung']);
        DB::table('cities')->insert(['id' => 1903, 'province_id' => 19, 'name' => 'Kab. Bangka Selatan']);
        DB::table('cities')->insert(['id' => 1904, 'province_id' => 19, 'name' => 'Kab. Bangka Tengah']);
        DB::table('cities')->insert(['id' => 1905, 'province_id' => 19, 'name' => 'Kab. Bangka Barat']);
        DB::table('cities')->insert(['id' => 1906, 'province_id' => 19, 'name' => 'Kab. Belitung Timur']);
        DB::table('cities')->insert(['id' => 1971, 'province_id' => 19, 'name' => 'Kota Pangkal Pinang']);
        DB::table('cities')->insert(['id' => 2101, 'province_id' => 21, 'name' => 'Kab. Bintan']);
        DB::table('cities')->insert(['id' => 2102, 'province_id' => 21, 'name' => 'Kab. Karimun']);
        DB::table('cities')->insert(['id' => 2103, 'province_id' => 21, 'name' => 'Kab. Natuna']);
        DB::table('cities')->insert(['id' => 2104, 'province_id' => 21, 'name' => 'Kab. Lingga']);
        DB::table('cities')->insert(['id' => 2105, 'province_id' => 21, 'name' => 'Kab. Kepulauan Anambas']);
        DB::table('cities')->insert(['id' => 2171, 'province_id' => 21, 'name' => 'Kota Batam']);
        DB::table('cities')->insert(['id' => 2172, 'province_id' => 21, 'name' => 'Kota Tanjung Pinang']);
        DB::table('cities')->insert(['id' => 3101, 'province_id' => 31, 'name' => 'Kab. Adm. Kep. Seribu']);
        DB::table('cities')->insert(['id' => 3171, 'province_id' => 31, 'name' => 'Kota Adm. Jakarta Pusat']);
        DB::table('cities')->insert(['id' => 3172, 'province_id' => 31, 'name' => 'Kota Adm. Jakarta Utara']);
        DB::table('cities')->insert(['id' => 3173, 'province_id' => 31, 'name' => 'Kota Adm. Jakarta Barat']);
        DB::table('cities')->insert(['id' => 3174, 'province_id' => 31, 'name' => 'Kota Adm. Jakarta Selatan']);
        DB::table('cities')->insert(['id' => 3175, 'province_id' => 31, 'name' => 'Kota Adm. Jakarta Timur']);
        DB::table('cities')->insert(['id' => 3201, 'province_id' => 32, 'name' => 'Kab. Bogor']);
        DB::table('cities')->insert(['id' => 3202, 'province_id' => 32, 'name' => 'Kab. Sukabumi']);
        DB::table('cities')->insert(['id' => 3203, 'province_id' => 32, 'name' => 'Kab. Cianjur']);
        DB::table('cities')->insert(['id' => 3204, 'province_id' => 32, 'name' => 'Kab. Bandung']);
        DB::table('cities')->insert(['id' => 3205, 'province_id' => 32, 'name' => 'Kab. Garut']);
        DB::table('cities')->insert(['id' => 3206, 'province_id' => 32, 'name' => 'Kab. Tasikmalaya']);
        DB::table('cities')->insert(['id' => 3207, 'province_id' => 32, 'name' => 'Kab. Ciamis']);
        DB::table('cities')->insert(['id' => 3208, 'province_id' => 32, 'name' => 'Kab. Kuningan']);
        DB::table('cities')->insert(['id' => 3209, 'province_id' => 32, 'name' => 'Kab. Cirebon']);
        DB::table('cities')->insert(['id' => 3210, 'province_id' => 32, 'name' => 'Kab. Majalengka']);
        DB::table('cities')->insert(['id' => 3211, 'province_id' => 32, 'name' => 'Kab. Sumedang']);
        DB::table('cities')->insert(['id' => 3212, 'province_id' => 32, 'name' => 'Kab. Indramayu']);
        DB::table('cities')->insert(['id' => 3213, 'province_id' => 32, 'name' => 'Kab. Subang']);
        DB::table('cities')->insert(['id' => 3214, 'province_id' => 32, 'name' => 'Kab. Purwakarta']);
        DB::table('cities')->insert(['id' => 3215, 'province_id' => 32, 'name' => 'Kab. Karawang']);
        DB::table('cities')->insert(['id' => 3216, 'province_id' => 32, 'name' => 'Kab. Bekasi']);
        DB::table('cities')->insert(['id' => 3217, 'province_id' => 32, 'name' => 'Kab. Bandung Barat']);
        DB::table('cities')->insert(['id' => 3218, 'province_id' => 32, 'name' => 'Kab. Pangandaran']);
        DB::table('cities')->insert(['id' => 3271, 'province_id' => 32, 'name' => 'Kota Bogor']);
        DB::table('cities')->insert(['id' => 3272, 'province_id' => 32, 'name' => 'Kota Sukabumi']);
        DB::table('cities')->insert(['id' => 3273, 'province_id' => 32, 'name' => 'Kota Bandung']);
        DB::table('cities')->insert(['id' => 3274, 'province_id' => 32, 'name' => 'Kota Cirebon']);
        DB::table('cities')->insert(['id' => 3275, 'province_id' => 32, 'name' => 'Kota Bekasi']);
        DB::table('cities')->insert(['id' => 3276, 'province_id' => 32, 'name' => 'Kota Depok']);
        DB::table('cities')->insert(['id' => 3277, 'province_id' => 32, 'name' => 'Kota Cimahi']);
        DB::table('cities')->insert(['id' => 3278, 'province_id' => 32, 'name' => 'Kota Tasikmalaya']);
        DB::table('cities')->insert(['id' => 3279, 'province_id' => 32, 'name' => 'Kota Banjar']);
        DB::table('cities')->insert(['id' => 3301, 'province_id' => 33, 'name' => 'Kab. Cilacap']);
        DB::table('cities')->insert(['id' => 3302, 'province_id' => 33, 'name' => 'Kab. Banyumas']);
        DB::table('cities')->insert(['id' => 3303, 'province_id' => 33, 'name' => 'Kab. Purbalingga']);
        DB::table('cities')->insert(['id' => 3304, 'province_id' => 33, 'name' => 'Kab. Banjarnegara']);
        DB::table('cities')->insert(['id' => 3305, 'province_id' => 33, 'name' => 'Kab. Kebumen']);
        DB::table('cities')->insert(['id' => 3306, 'province_id' => 33, 'name' => 'Kab. Purworejo']);
        DB::table('cities')->insert(['id' => 3307, 'province_id' => 33, 'name' => 'Kab. Wonosobo']);
        DB::table('cities')->insert(['id' => 3308, 'province_id' => 33, 'name' => 'Kab. Magelang']);
        DB::table('cities')->insert(['id' => 3309, 'province_id' => 33, 'name' => 'Kab. Boyolali']);
        DB::table('cities')->insert(['id' => 3310, 'province_id' => 33, 'name' => 'Kab. Klaten']);
        DB::table('cities')->insert(['id' => 3311, 'province_id' => 33, 'name' => 'Kab. Sukoharjo']);
        DB::table('cities')->insert(['id' => 3312, 'province_id' => 33, 'name' => 'Kab. Wonogiri']);
        DB::table('cities')->insert(['id' => 3313, 'province_id' => 33, 'name' => 'Kab. Karanganyar']);
        DB::table('cities')->insert(['id' => 3314, 'province_id' => 33, 'name' => 'Kab. Sragen']);
        DB::table('cities')->insert(['id' => 3315, 'province_id' => 33, 'name' => 'Kab. Grobogan']);
        DB::table('cities')->insert(['id' => 3316, 'province_id' => 33, 'name' => 'Kab. Blora']);
        DB::table('cities')->insert(['id' => 3317, 'province_id' => 33, 'name' => 'Kab. Rembang']);
        DB::table('cities')->insert(['id' => 3318, 'province_id' => 33, 'name' => 'Kab. Pati']);
        DB::table('cities')->insert(['id' => 3319, 'province_id' => 33, 'name' => 'Kab. Kudus']);
        DB::table('cities')->insert(['id' => 3320, 'province_id' => 33, 'name' => 'Kab. Jepara']);
        DB::table('cities')->insert(['id' => 3321, 'province_id' => 33, 'name' => 'Kab. Demak']);
        DB::table('cities')->insert(['id' => 3322, 'province_id' => 33, 'name' => 'Kab. Semarang']);
        DB::table('cities')->insert(['id' => 3323, 'province_id' => 33, 'name' => 'Kab. Temanggung']);
        DB::table('cities')->insert(['id' => 3324, 'province_id' => 33, 'name' => 'Kab. Kendal']);
        DB::table('cities')->insert(['id' => 3325, 'province_id' => 33, 'name' => 'Kab. Batang']);
        DB::table('cities')->insert(['id' => 3326, 'province_id' => 33, 'name' => 'Kab. Pekalongan']);
        DB::table('cities')->insert(['id' => 3327, 'province_id' => 33, 'name' => 'Kab. Pemalang']);
        DB::table('cities')->insert(['id' => 3328, 'province_id' => 33, 'name' => 'Kab. Tegal']);
        DB::table('cities')->insert(['id' => 3329, 'province_id' => 33, 'name' => 'Kab. Brebes']);
        DB::table('cities')->insert(['id' => 3371, 'province_id' => 33, 'name' => 'Kota Magelang']);
        DB::table('cities')->insert(['id' => 3372, 'province_id' => 33, 'name' => 'Kota Surakarta']);
        DB::table('cities')->insert(['id' => 3373, 'province_id' => 33, 'name' => 'Kota Salatiga']);
        DB::table('cities')->insert(['id' => 3374, 'province_id' => 33, 'name' => 'Kota Semarang']);
        DB::table('cities')->insert(['id' => 3375, 'province_id' => 33, 'name' => 'Kota Pekalongan']);
        DB::table('cities')->insert(['id' => 3376, 'province_id' => 33, 'name' => 'Kota Tegal']);
        DB::table('cities')->insert(['id' => 3401, 'province_id' => 34, 'name' => 'Kab. Kulon Progo']);
        DB::table('cities')->insert(['id' => 3402, 'province_id' => 34, 'name' => 'Kab. Bantul']);
        DB::table('cities')->insert(['id' => 3403, 'province_id' => 34, 'name' => 'Kab. Gunung Kidul']);
        DB::table('cities')->insert(['id' => 3404, 'province_id' => 34, 'name' => 'Kab. Sleman']);
        DB::table('cities')->insert(['id' => 3471, 'province_id' => 34, 'name' => 'Kota Yogyakarta']);
        DB::table('cities')->insert(['id' => 3501, 'province_id' => 35, 'name' => 'Kab. Pacitan']);
        DB::table('cities')->insert(['id' => 3502, 'province_id' => 35, 'name' => 'Kab. Ponorogo']);
        DB::table('cities')->insert(['id' => 3503, 'province_id' => 35, 'name' => 'Kab. Trenggalek']);
        DB::table('cities')->insert(['id' => 3504, 'province_id' => 35, 'name' => 'Kab. Tulungagung']);
        DB::table('cities')->insert(['id' => 3505, 'province_id' => 35, 'name' => 'Kab. Blitar']);
        DB::table('cities')->insert(['id' => 3506, 'province_id' => 35, 'name' => 'Kab. Kediri']);
        DB::table('cities')->insert(['id' => 3507, 'province_id' => 35, 'name' => 'Kab. Malang']);
        DB::table('cities')->insert(['id' => 3508, 'province_id' => 35, 'name' => 'Kab. Lumajang']);
        DB::table('cities')->insert(['id' => 3509, 'province_id' => 35, 'name' => 'Kab. Jember']);
        DB::table('cities')->insert(['id' => 3510, 'province_id' => 35, 'name' => 'Kab. Banyuwangi']);
        DB::table('cities')->insert(['id' => 3511, 'province_id' => 35, 'name' => 'Kab. Bondowoso']);
        DB::table('cities')->insert(['id' => 3512, 'province_id' => 35, 'name' => 'Kab. Situbondo']);
        DB::table('cities')->insert(['id' => 3513, 'province_id' => 35, 'name' => 'Kab. Probolinggo']);
        DB::table('cities')->insert(['id' => 3514, 'province_id' => 35, 'name' => 'Kab. Pasuruan']);
        DB::table('cities')->insert(['id' => 3515, 'province_id' => 35, 'name' => 'Kab. Sidoarjo']);
        DB::table('cities')->insert(['id' => 3516, 'province_id' => 35, 'name' => 'Kab. Mojokerto']);
        DB::table('cities')->insert(['id' => 3517, 'province_id' => 35, 'name' => 'Kab. Jombang']);
        DB::table('cities')->insert(['id' => 3518, 'province_id' => 35, 'name' => 'Kab. Nganjuk']);
        DB::table('cities')->insert(['id' => 3519, 'province_id' => 35, 'name' => 'Kab. Madiun']);
        DB::table('cities')->insert(['id' => 3520, 'province_id' => 35, 'name' => 'Kab. Magetan']);
        DB::table('cities')->insert(['id' => 3521, 'province_id' => 35, 'name' => 'Kab. Ngawi']);
        DB::table('cities')->insert(['id' => 3522, 'province_id' => 35, 'name' => 'Kab. Bojonegoro']);
        DB::table('cities')->insert(['id' => 3523, 'province_id' => 35, 'name' => 'Kab. Tuban']);
        DB::table('cities')->insert(['id' => 3524, 'province_id' => 35, 'name' => 'Kab. Lamongan']);
        DB::table('cities')->insert(['id' => 3525, 'province_id' => 35, 'name' => 'Kab. Gresik']);
        DB::table('cities')->insert(['id' => 3526, 'province_id' => 35, 'name' => 'Kab. Bangkalan']);
        DB::table('cities')->insert(['id' => 3527, 'province_id' => 35, 'name' => 'Kab. Sampang']);
        DB::table('cities')->insert(['id' => 3528, 'province_id' => 35, 'name' => 'Kab. Pamekasan']);
        DB::table('cities')->insert(['id' => 3529, 'province_id' => 35, 'name' => 'Kab. Sumenep']);
        DB::table('cities')->insert(['id' => 3571, 'province_id' => 35, 'name' => 'Kota Kediri']);
        DB::table('cities')->insert(['id' => 3572, 'province_id' => 35, 'name' => 'Kota Blitar']);
        DB::table('cities')->insert(['id' => 3573, 'province_id' => 35, 'name' => 'Kota Malang']);
        DB::table('cities')->insert(['id' => 3574, 'province_id' => 35, 'name' => 'Kota Probolinggo']);
        DB::table('cities')->insert(['id' => 3575, 'province_id' => 35, 'name' => 'Kota Pasuruan']);
        DB::table('cities')->insert(['id' => 3576, 'province_id' => 35, 'name' => 'Kota Mojokerto']);
        DB::table('cities')->insert(['id' => 3577, 'province_id' => 35, 'name' => 'Kota Madiun']);
        DB::table('cities')->insert(['id' => 3578, 'province_id' => 35, 'name' => 'Kota Surabaya']);
        DB::table('cities')->insert(['id' => 3579, 'province_id' => 35, 'name' => 'Kota Batu']);
        DB::table('cities')->insert(['id' => 3601, 'province_id' => 36, 'name' => 'Kab. Pandeglang']);
        DB::table('cities')->insert(['id' => 3602, 'province_id' => 36, 'name' => 'Kab. Lebak']);
        DB::table('cities')->insert(['id' => 3603, 'province_id' => 36, 'name' => 'Kab. Tangerang']);
        DB::table('cities')->insert(['id' => 3604, 'province_id' => 36, 'name' => 'Kab. Serang']);
        DB::table('cities')->insert(['id' => 3671, 'province_id' => 36, 'name' => 'Kota Tangerang']);
        DB::table('cities')->insert(['id' => 3672, 'province_id' => 36, 'name' => 'Kota Cilegon']);
        DB::table('cities')->insert(['id' => 3673, 'province_id' => 36, 'name' => 'Kota Serang']);
        DB::table('cities')->insert(['id' => 3674, 'province_id' => 36, 'name' => 'Kota Tangerang Selatan']);
        DB::table('cities')->insert(['id' => 5101, 'province_id' => 51, 'name' => 'Kab. Jembrana']);
        DB::table('cities')->insert(['id' => 5102, 'province_id' => 51, 'name' => 'Kab. Tabanan']);
        DB::table('cities')->insert(['id' => 5103, 'province_id' => 51, 'name' => 'Kab. Badung']);
        DB::table('cities')->insert(['id' => 5104, 'province_id' => 51, 'name' => 'Kab. Gianyar']);
        DB::table('cities')->insert(['id' => 5105, 'province_id' => 51, 'name' => 'Kab. Klungkung']);
        DB::table('cities')->insert(['id' => 5106, 'province_id' => 51, 'name' => 'Kab. Bangli']);
        DB::table('cities')->insert(['id' => 5107, 'province_id' => 51, 'name' => 'Kab. Karangasem']);
        DB::table('cities')->insert(['id' => 5108, 'province_id' => 51, 'name' => 'Kab. Buleleng']);
        DB::table('cities')->insert(['id' => 5171, 'province_id' => 51, 'name' => 'Kota Denpasar']);
        DB::table('cities')->insert(['id' => 5201, 'province_id' => 52, 'name' => 'Kab. Lombok Barat']);
        DB::table('cities')->insert(['id' => 5202, 'province_id' => 52, 'name' => 'Kab. Lombok Tengah']);
        DB::table('cities')->insert(['id' => 5203, 'province_id' => 52, 'name' => 'Kab. Lombok Timur']);
        DB::table('cities')->insert(['id' => 5204, 'province_id' => 52, 'name' => 'Kab. Sumbawa']);
        DB::table('cities')->insert(['id' => 5205, 'province_id' => 52, 'name' => 'Kab. Dompu']);
        DB::table('cities')->insert(['id' => 5206, 'province_id' => 52, 'name' => 'Kab. Bima']);
        DB::table('cities')->insert(['id' => 5207, 'province_id' => 52, 'name' => 'Kab. Sumbawa Barat']);
        DB::table('cities')->insert(['id' => 5208, 'province_id' => 52, 'name' => 'Kab. Lombok Utara']);
        DB::table('cities')->insert(['id' => 5271, 'province_id' => 52, 'name' => 'Kota Mataram']);
        DB::table('cities')->insert(['id' => 5272, 'province_id' => 52, 'name' => 'Kota Bima']);
        DB::table('cities')->insert(['id' => 5301, 'province_id' => 53, 'name' => 'Kab. Kupang']);
        DB::table('cities')->insert(['id' => 5302, 'province_id' => 53, 'name' => 'Kab Timor Tengah Selatan']);
        DB::table('cities')->insert(['id' => 5303, 'province_id' => 53, 'name' => 'Kab. Timor Tengah Utara']);
        DB::table('cities')->insert(['id' => 5304, 'province_id' => 53, 'name' => 'Kab. Belu']);
        DB::table('cities')->insert(['id' => 5305, 'province_id' => 53, 'name' => 'Kab. Alor']);
        DB::table('cities')->insert(['id' => 5306, 'province_id' => 53, 'name' => 'Kab. Flores Timur']);
        DB::table('cities')->insert(['id' => 5307, 'province_id' => 53, 'name' => 'Kab. Sikka']);
        DB::table('cities')->insert(['id' => 5308, 'province_id' => 53, 'name' => 'Kab. Ende']);
        DB::table('cities')->insert(['id' => 5309, 'province_id' => 53, 'name' => 'Kab. Ngada']);
        DB::table('cities')->insert(['id' => 5310, 'province_id' => 53, 'name' => 'Kab. Manggarai']);
        DB::table('cities')->insert(['id' => 5311, 'province_id' => 53, 'name' => 'Kab. Sumba Timur']);
        DB::table('cities')->insert(['id' => 5312, 'province_id' => 53, 'name' => 'Kab. Sumba Barat']);
        DB::table('cities')->insert(['id' => 5313, 'province_id' => 53, 'name' => 'Kab. Lembata']);
        DB::table('cities')->insert(['id' => 5314, 'province_id' => 53, 'name' => 'Kab. Rote Ndao']);
        DB::table('cities')->insert(['id' => 5315, 'province_id' => 53, 'name' => 'Kab. Manggarai Barat']);
        DB::table('cities')->insert(['id' => 5316, 'province_id' => 53, 'name' => 'Kab. Nagekeo']);
        DB::table('cities')->insert(['id' => 5317, 'province_id' => 53, 'name' => 'Kab. Sumba Tengah']);
        DB::table('cities')->insert(['id' => 5318, 'province_id' => 53, 'name' => 'Kab. Sumba Barat Daya']);
        DB::table('cities')->insert(['id' => 5319, 'province_id' => 53, 'name' => 'Kab. Manggarai Timur']);
        DB::table('cities')->insert(['id' => 5320, 'province_id' => 53, 'name' => 'Kab. Sabu Raijua']);
        DB::table('cities')->insert(['id' => 5321, 'province_id' => 53, 'name' => 'Kab. Malaka']);
        DB::table('cities')->insert(['id' => 5371, 'province_id' => 53, 'name' => 'Kota Kupang']);
        DB::table('cities')->insert(['id' => 6101, 'province_id' => 61, 'name' => 'Kab. Sambas']);
        DB::table('cities')->insert(['id' => 6102, 'province_id' => 61, 'name' => 'Kab. Mempawah']);
        DB::table('cities')->insert(['id' => 6103, 'province_id' => 61, 'name' => 'Kab. Sanggau']);
        DB::table('cities')->insert(['id' => 6104, 'province_id' => 61, 'name' => 'Kab. Ketapang']);
        DB::table('cities')->insert(['id' => 6105, 'province_id' => 61, 'name' => 'Kab. Sintang']);
        DB::table('cities')->insert(['id' => 6106, 'province_id' => 61, 'name' => 'Kab. Kapuas Hulu']);
        DB::table('cities')->insert(['id' => 6107, 'province_id' => 61, 'name' => 'Kab. Bengkayang']);
        DB::table('cities')->insert(['id' => 6108, 'province_id' => 61, 'name' => 'Kab. Landak']);
        DB::table('cities')->insert(['id' => 6109, 'province_id' => 61, 'name' => 'Kab. Sekadau']);
        DB::table('cities')->insert(['id' => 6110, 'province_id' => 61, 'name' => 'Kab. Melawi']);
        DB::table('cities')->insert(['id' => 6111, 'province_id' => 61, 'name' => 'Kab. Kayong Utara']);
        DB::table('cities')->insert(['id' => 6112, 'province_id' => 61, 'name' => 'Kab. Kubu Raya']);
        DB::table('cities')->insert(['id' => 6171, 'province_id' => 61, 'name' => 'Kota Pontianak']);
        DB::table('cities')->insert(['id' => 6172, 'province_id' => 61, 'name' => 'Kota Singkawang']);
        DB::table('cities')->insert(['id' => 6201, 'province_id' => 62, 'name' => 'Kab. Kotawaringin Barat']);
        DB::table('cities')->insert(['id' => 6202, 'province_id' => 62, 'name' => 'Kab. Kotawaringin Timur']);
        DB::table('cities')->insert(['id' => 6203, 'province_id' => 62, 'name' => 'Kab. Kapuas']);
        DB::table('cities')->insert(['id' => 6204, 'province_id' => 62, 'name' => 'Kab. Barito Selatan']);
        DB::table('cities')->insert(['id' => 6205, 'province_id' => 62, 'name' => 'Kab. Barito Utara']);
        DB::table('cities')->insert(['id' => 6206, 'province_id' => 62, 'name' => 'Kab. Katingan']);
        DB::table('cities')->insert(['id' => 6207, 'province_id' => 62, 'name' => 'Kab. Seruyan']);
        DB::table('cities')->insert(['id' => 6208, 'province_id' => 62, 'name' => 'Kab. Sukamara']);
        DB::table('cities')->insert(['id' => 6209, 'province_id' => 62, 'name' => 'Kab. Lamandau']);
        DB::table('cities')->insert(['id' => 6210, 'province_id' => 62, 'name' => 'Kab. Gunung Mas']);
        DB::table('cities')->insert(['id' => 6211, 'province_id' => 62, 'name' => 'Kab. Pulang Pisau']);
        DB::table('cities')->insert(['id' => 6212, 'province_id' => 62, 'name' => 'Kab. Murung Raya']);
        DB::table('cities')->insert(['id' => 6213, 'province_id' => 62, 'name' => 'Kab. Barito Timur']);
        DB::table('cities')->insert(['id' => 6271, 'province_id' => 62, 'name' => 'Kota Palangkaraya']);
        DB::table('cities')->insert(['id' => 6301, 'province_id' => 63, 'name' => 'Kab. Tanah Laut']);
        DB::table('cities')->insert(['id' => 6302, 'province_id' => 63, 'name' => 'Kab. Kotabaru']);
        DB::table('cities')->insert(['id' => 6303, 'province_id' => 63, 'name' => 'Kab. Banjar']);
        DB::table('cities')->insert(['id' => 6304, 'province_id' => 63, 'name' => 'Kab. Barito Kuala']);
        DB::table('cities')->insert(['id' => 6305, 'province_id' => 63, 'name' => 'Kab. Tapin']);
        DB::table('cities')->insert(['id' => 6306, 'province_id' => 63, 'name' => 'Kab. Hulu Sungai Selatan']);
        DB::table('cities')->insert(['id' => 6307, 'province_id' => 63, 'name' => 'Kab. Hulu Sungai Tengah']);
        DB::table('cities')->insert(['id' => 6308, 'province_id' => 63, 'name' => 'Kab. Hulu Sungai Utara']);
        DB::table('cities')->insert(['id' => 6309, 'province_id' => 63, 'name' => 'Kab. Tabalong']);
        DB::table('cities')->insert(['id' => 6310, 'province_id' => 63, 'name' => 'Kab. Tanah Bumbu']);
        DB::table('cities')->insert(['id' => 6311, 'province_id' => 63, 'name' => 'Kab. Balangan']);
        DB::table('cities')->insert(['id' => 6371, 'province_id' => 63, 'name' => 'Kota Banjarmasin']);
        DB::table('cities')->insert(['id' => 6372, 'province_id' => 63, 'name' => 'Kota Banjarbaru']);
        DB::table('cities')->insert(['id' => 6401, 'province_id' => 64, 'name' => 'Kab. Paser']);
        DB::table('cities')->insert(['id' => 6402, 'province_id' => 64, 'name' => 'Kab. Kutai Kartanegara']);
        DB::table('cities')->insert(['id' => 6403, 'province_id' => 64, 'name' => 'Kab. Berau']);
        DB::table('cities')->insert(['id' => 6407, 'province_id' => 64, 'name' => 'Kab. Kutai Barat']);
        DB::table('cities')->insert(['id' => 6408, 'province_id' => 64, 'name' => 'Kab. Kutai Timur']);
        DB::table('cities')->insert(['id' => 6409, 'province_id' => 64, 'name' => 'Kab. Penajam Paser Utara']);
        DB::table('cities')->insert(['id' => 6411, 'province_id' => 64, 'name' => 'Kab. Mahakam Ulu']);
        DB::table('cities')->insert(['id' => 6471, 'province_id' => 64, 'name' => 'Kota Balikpapan']);
        DB::table('cities')->insert(['id' => 6472, 'province_id' => 64, 'name' => 'Kota Samarinda']);
        DB::table('cities')->insert(['id' => 6474, 'province_id' => 64, 'name' => 'Kota Bontang']);
        DB::table('cities')->insert(['id' => 6501, 'province_id' => 65, 'name' => 'Kab. Bulungan']);
        DB::table('cities')->insert(['id' => 6502, 'province_id' => 65, 'name' => 'Kab. Malinau']);
        DB::table('cities')->insert(['id' => 6503, 'province_id' => 65, 'name' => 'Kab. Nunukan']);
        DB::table('cities')->insert(['id' => 6504, 'province_id' => 65, 'name' => 'Kab. Tana Tidung']);
        DB::table('cities')->insert(['id' => 6571, 'province_id' => 65, 'name' => 'Kota Tarakan']);
        DB::table('cities')->insert(['id' => 7101, 'province_id' => 71, 'name' => 'Kab. Bolaang Mongondow']);
        DB::table('cities')->insert(['id' => 7102, 'province_id' => 71, 'name' => 'Kab. Minahasa']);
        DB::table('cities')->insert(['id' => 7103, 'province_id' => 71, 'name' => 'Kab. Kepulauan Sangihe']);
        DB::table('cities')->insert(['id' => 7104, 'province_id' => 71, 'name' => 'Kab. Kepulauan Talaud']);
        DB::table('cities')->insert(['id' => 7105, 'province_id' => 71, 'name' => 'Kab. Minahasa Selatan']);
        DB::table('cities')->insert(['id' => 7106, 'province_id' => 71, 'name' => 'Kab. Minahasa Utara']);
        DB::table('cities')->insert(['id' => 7107, 'province_id' => 71, 'name' => 'Kab. Minahasa Tenggara']);
        DB::table('cities')->insert(['id' => 7108, 'province_id' => 71, 'name' => 'Kab. Bolaang Mongondow Utara']);
        DB::table('cities')->insert(['id' => 7109, 'province_id' => 71, 'name' => 'Kab. Kep. Siau Tagulandang Biaro']);
        DB::table('cities')->insert(['id' => 7110, 'province_id' => 71, 'name' => 'Kab. Bolaang Mongondow Timur']);
        DB::table('cities')->insert(['id' => 7111, 'province_id' => 71, 'name' => 'Kab. Bolaang Mongondow Selatan']);
        DB::table('cities')->insert(['id' => 7171, 'province_id' => 71, 'name' => 'Kota Manado']);
        DB::table('cities')->insert(['id' => 7172, 'province_id' => 71, 'name' => 'Kota Bitung']);
        DB::table('cities')->insert(['id' => 7173, 'province_id' => 71, 'name' => 'Kota Tomohon']);
        DB::table('cities')->insert(['id' => 7174, 'province_id' => 71, 'name' => 'Kota Kotamobagu']);
        DB::table('cities')->insert(['id' => 7201, 'province_id' => 72, 'name' => 'Kab. Banggai']);
        DB::table('cities')->insert(['id' => 7202, 'province_id' => 72, 'name' => 'Kab. Poso']);
        DB::table('cities')->insert(['id' => 7203, 'province_id' => 72, 'name' => 'Kab. Donggala']);
        DB::table('cities')->insert(['id' => 7204, 'province_id' => 72, 'name' => 'Kab. Toli Toli']);
        DB::table('cities')->insert(['id' => 7205, 'province_id' => 72, 'name' => 'Kab. Buol']);
        DB::table('cities')->insert(['id' => 7206, 'province_id' => 72, 'name' => 'Kab. Morowali']);
        DB::table('cities')->insert(['id' => 7207, 'province_id' => 72, 'name' => 'Kab. Banggai Kepulauan']);
        DB::table('cities')->insert(['id' => 7208, 'province_id' => 72, 'name' => 'Kab. Parigi Moutong']);
        DB::table('cities')->insert(['id' => 7209, 'province_id' => 72, 'name' => 'Kab. Tojo Una Una']);
        DB::table('cities')->insert(['id' => 7210, 'province_id' => 72, 'name' => 'Kab. Sigi']);
        DB::table('cities')->insert(['id' => 7211, 'province_id' => 72, 'name' => 'Kab. Banggai Laut']);
        DB::table('cities')->insert(['id' => 7212, 'province_id' => 72, 'name' => 'Kab. Morowali Utara']);
        DB::table('cities')->insert(['id' => 7271, 'province_id' => 72, 'name' => 'Kota Palu']);
        DB::table('cities')->insert(['id' => 7301, 'province_id' => 73, 'name' => 'Kab. Kepulauan Selayar']);
        DB::table('cities')->insert(['id' => 7302, 'province_id' => 73, 'name' => 'Kab. Bulukumba']);
        DB::table('cities')->insert(['id' => 7303, 'province_id' => 73, 'name' => 'Kab. Bantaeng']);
        DB::table('cities')->insert(['id' => 7304, 'province_id' => 73, 'name' => 'Kab. Jeneponto']);
        DB::table('cities')->insert(['id' => 7305, 'province_id' => 73, 'name' => 'Kab. Takalar']);
        DB::table('cities')->insert(['id' => 7306, 'province_id' => 73, 'name' => 'Kab. Gowa']);
        DB::table('cities')->insert(['id' => 7307, 'province_id' => 73, 'name' => 'Kab. Sinjai']);
        DB::table('cities')->insert(['id' => 7308, 'province_id' => 73, 'name' => 'Kab. Bone']);
        DB::table('cities')->insert(['id' => 7309, 'province_id' => 73, 'name' => 'Kab. Maros']);
        DB::table('cities')->insert(['id' => 7310, 'province_id' => 73, 'name' => 'Kab. Pangkajene Kepulauan']);
        DB::table('cities')->insert(['id' => 7311, 'province_id' => 73, 'name' => 'Kab. Barru']);
        DB::table('cities')->insert(['id' => 7312, 'province_id' => 73, 'name' => 'Kab. Soppeng']);
        DB::table('cities')->insert(['id' => 7313, 'province_id' => 73, 'name' => 'Kab. Wajo']);
        DB::table('cities')->insert(['id' => 7314, 'province_id' => 73, 'name' => 'Kab. Sidenreng Rappang']);
        DB::table('cities')->insert(['id' => 7315, 'province_id' => 73, 'name' => 'Kab. Pinrang']);
        DB::table('cities')->insert(['id' => 7316, 'province_id' => 73, 'name' => 'Kab. Enrekang']);
        DB::table('cities')->insert(['id' => 7317, 'province_id' => 73, 'name' => 'Kab. Luwu']);
        DB::table('cities')->insert(['id' => 7318, 'province_id' => 73, 'name' => 'Kab. Tana Toraja']);
        DB::table('cities')->insert(['id' => 7322, 'province_id' => 73, 'name' => 'Kab. Luwu Utara']);
        DB::table('cities')->insert(['id' => 7324, 'province_id' => 73, 'name' => 'Kab. Luwu Timur']);
        DB::table('cities')->insert(['id' => 7326, 'province_id' => 73, 'name' => 'Kab. Toraja Utara']);
        DB::table('cities')->insert(['id' => 7371, 'province_id' => 73, 'name' => 'Kota Makassar']);
        DB::table('cities')->insert(['id' => 7372, 'province_id' => 73, 'name' => 'Kota Pare Pare']);
        DB::table('cities')->insert(['id' => 7373, 'province_id' => 73, 'name' => 'Kota Palopo']);
        DB::table('cities')->insert(['id' => 7401, 'province_id' => 74, 'name' => 'Kab. Kolaka']);
        DB::table('cities')->insert(['id' => 7402, 'province_id' => 74, 'name' => 'Kab. Konawe']);
        DB::table('cities')->insert(['id' => 7403, 'province_id' => 74, 'name' => 'Kab. Muna']);
        DB::table('cities')->insert(['id' => 7404, 'province_id' => 74, 'name' => 'Kab. Buton']);
        DB::table('cities')->insert(['id' => 7405, 'province_id' => 74, 'name' => 'Kab. Konawe Selatan']);
        DB::table('cities')->insert(['id' => 7406, 'province_id' => 74, 'name' => 'Kab. Bombana']);
        DB::table('cities')->insert(['id' => 7407, 'province_id' => 74, 'name' => 'Kab. Wakatobi']);
        DB::table('cities')->insert(['id' => 7408, 'province_id' => 74, 'name' => 'Kab. Kolaka Utara']);
        DB::table('cities')->insert(['id' => 7409, 'province_id' => 74, 'name' => 'Kab. Konawe Utara']);
        DB::table('cities')->insert(['id' => 7410, 'province_id' => 74, 'name' => 'Kab. Buton Utara']);
        DB::table('cities')->insert(['id' => 7411, 'province_id' => 74, 'name' => 'Kab. Kolaka Timur']);
        DB::table('cities')->insert(['id' => 7412, 'province_id' => 74, 'name' => 'Kab. Konawe Kepulauan']);
        DB::table('cities')->insert(['id' => 7413, 'province_id' => 74, 'name' => 'Kab. Muna Barat']);
        DB::table('cities')->insert(['id' => 7414, 'province_id' => 74, 'name' => 'Kab. Buton Tengah']);
        DB::table('cities')->insert(['id' => 7415, 'province_id' => 74, 'name' => 'Kab. Buton Selatan']);
        DB::table('cities')->insert(['id' => 7471, 'province_id' => 74, 'name' => 'Kota Kendari']);
        DB::table('cities')->insert(['id' => 7472, 'province_id' => 74, 'name' => 'Kota Bau Bau']);
        DB::table('cities')->insert(['id' => 7501, 'province_id' => 75, 'name' => 'Kab. Gorontalo']);
        DB::table('cities')->insert(['id' => 7502, 'province_id' => 75, 'name' => 'Kab. Boalemo']);
        DB::table('cities')->insert(['id' => 7503, 'province_id' => 75, 'name' => 'Kab. Bone Bolango']);
        DB::table('cities')->insert(['id' => 7504, 'province_id' => 75, 'name' => 'Kab. Pahuwato']);
        DB::table('cities')->insert(['id' => 7505, 'province_id' => 75, 'name' => 'Kab. Gorontalo Utara']);
        DB::table('cities')->insert(['id' => 7571, 'province_id' => 75, 'name' => 'Kota Gorontalo']);
        DB::table('cities')->insert(['id' => 7601, 'province_id' => 76, 'name' => 'Kab. Mamuju Utara']);
        DB::table('cities')->insert(['id' => 7602, 'province_id' => 76, 'name' => 'Kab. Mamuju']);
        DB::table('cities')->insert(['id' => 7603, 'province_id' => 76, 'name' => 'Kab. Mamasa']);
        DB::table('cities')->insert(['id' => 7604, 'province_id' => 76, 'name' => 'Kab. Polewali Mandar']);
        DB::table('cities')->insert(['id' => 7605, 'province_id' => 76, 'name' => 'Kab. Majene']);
        DB::table('cities')->insert(['id' => 7606, 'province_id' => 76, 'name' => 'Kab. Mamuju Tengah']);
        DB::table('cities')->insert(['id' => 8101, 'province_id' => 81, 'name' => 'Kab. Maluku Tengah']);
        DB::table('cities')->insert(['id' => 8102, 'province_id' => 81, 'name' => 'Kab. Maluku Tenggara']);
        DB::table('cities')->insert(['id' => 8103, 'province_id' => 81, 'name' => 'Kab Maluku Tenggara Barat']);
        DB::table('cities')->insert(['id' => 8104, 'province_id' => 81, 'name' => 'Kab. Buru']);
        DB::table('cities')->insert(['id' => 8105, 'province_id' => 81, 'name' => 'Kab. Seram Bagian Timur']);
        DB::table('cities')->insert(['id' => 8106, 'province_id' => 81, 'name' => 'Kab. Seram Bagian Barat']);
        DB::table('cities')->insert(['id' => 8107, 'province_id' => 81, 'name' => 'Kab. Kepulauan Aru']);
        DB::table('cities')->insert(['id' => 8108, 'province_id' => 81, 'name' => 'Kab. Maluku Barat Daya']);
        DB::table('cities')->insert(['id' => 8109, 'province_id' => 81, 'name' => 'Kab. Buru Selatan']);
        DB::table('cities')->insert(['id' => 8171, 'province_id' => 81, 'name' => 'Kota Ambon']);
        DB::table('cities')->insert(['id' => 8172, 'province_id' => 81, 'name' => 'Kota Tual']);
        DB::table('cities')->insert(['id' => 8201, 'province_id' => 82, 'name' => 'Kab. Halmahera Barat']);
        DB::table('cities')->insert(['id' => 8202, 'province_id' => 82, 'name' => 'Kab. Halmahera Tengah']);
        DB::table('cities')->insert(['id' => 8203, 'province_id' => 82, 'name' => 'Kab. Halmahera Utara']);
        DB::table('cities')->insert(['id' => 8204, 'province_id' => 82, 'name' => 'Kab. Halmahera Selatan']);
        DB::table('cities')->insert(['id' => 8205, 'province_id' => 82, 'name' => 'Kab. Kepulauan Sula']);
        DB::table('cities')->insert(['id' => 8206, 'province_id' => 82, 'name' => 'Kab. Halmahera Timur']);
        DB::table('cities')->insert(['id' => 8207, 'province_id' => 82, 'name' => 'Kab. Pulau Morotai']);
        DB::table('cities')->insert(['id' => 8208, 'province_id' => 82, 'name' => 'Kab. Pulau Taliabu']);
        DB::table('cities')->insert(['id' => 8271, 'province_id' => 82, 'name' => 'Kota Ternate']);
        DB::table('cities')->insert(['id' => 8272, 'province_id' => 82, 'name' => 'Kota Tidore Kepulauan']);
        DB::table('cities')->insert(['id' => 9101, 'province_id' => 91, 'name' => 'Kab. Merauke']);
        DB::table('cities')->insert(['id' => 9102, 'province_id' => 91, 'name' => 'Kab. Jayawijaya']);
        DB::table('cities')->insert(['id' => 9103, 'province_id' => 91, 'name' => 'Kab. Jayapura']);
        DB::table('cities')->insert(['id' => 9104, 'province_id' => 91, 'name' => 'Kab. Nabire']);
        DB::table('cities')->insert(['id' => 9105, 'province_id' => 91, 'name' => 'Kab. Kepulauan Yapen']);
        DB::table('cities')->insert(['id' => 9106, 'province_id' => 91, 'name' => 'Kab. Biak Numfor']);
        DB::table('cities')->insert(['id' => 9107, 'province_id' => 91, 'name' => 'Kab. Puncak Jaya']);
        DB::table('cities')->insert(['id' => 9108, 'province_id' => 91, 'name' => 'Kab. Paniai']);
        DB::table('cities')->insert(['id' => 9109, 'province_id' => 91, 'name' => 'Kab. Mimika']);
        DB::table('cities')->insert(['id' => 9110, 'province_id' => 91, 'name' => 'Kab. Sarmi']);
        DB::table('cities')->insert(['id' => 9111, 'province_id' => 91, 'name' => 'Kab. Keerom']);
        DB::table('cities')->insert(['id' => 9112, 'province_id' => 91, 'name' => 'Kab Pegunungan Bintang']);
        DB::table('cities')->insert(['id' => 9113, 'province_id' => 91, 'name' => 'Kab. Yahukimo']);
        DB::table('cities')->insert(['id' => 9114, 'province_id' => 91, 'name' => 'Kab. Tolikara']);
        DB::table('cities')->insert(['id' => 9115, 'province_id' => 91, 'name' => 'Kab. Waropen']);
        DB::table('cities')->insert(['id' => 9116, 'province_id' => 91, 'name' => 'Kab. Boven Digoel']);
        DB::table('cities')->insert(['id' => 9117, 'province_id' => 91, 'name' => 'Kab. Mappi']);
        DB::table('cities')->insert(['id' => 9118, 'province_id' => 91, 'name' => 'Kab. Asmat']);
        DB::table('cities')->insert(['id' => 9119, 'province_id' => 91, 'name' => 'Kab. Supiori']);
        DB::table('cities')->insert(['id' => 9120, 'province_id' => 91, 'name' => 'Kab. Mamberamo Raya']);
        DB::table('cities')->insert(['id' => 9121, 'province_id' => 91, 'name' => 'Kab. Mamberamo Tengah']);
        DB::table('cities')->insert(['id' => 9122, 'province_id' => 91, 'name' => 'Kab. Yalimo']);
        DB::table('cities')->insert(['id' => 9123, 'province_id' => 91, 'name' => 'Kab. Lanny Jaya']);
        DB::table('cities')->insert(['id' => 9124, 'province_id' => 91, 'name' => 'Kab. Nduga']);
        DB::table('cities')->insert(['id' => 9125, 'province_id' => 91, 'name' => 'Kab. Puncak']);
        DB::table('cities')->insert(['id' => 9126, 'province_id' => 91, 'name' => 'Kab. Dogiyai']);
        DB::table('cities')->insert(['id' => 9127, 'province_id' => 91, 'name' => 'Kab. Intan Jaya']);
        DB::table('cities')->insert(['id' => 9128, 'province_id' => 91, 'name' => 'Kab. Deiyai']);
        DB::table('cities')->insert(['id' => 9171, 'province_id' => 91, 'name' => 'Kota Jayapura']);
        DB::table('cities')->insert(['id' => 9201, 'province_id' => 92, 'name' => 'Kab. Sorong']);
        DB::table('cities')->insert(['id' => 9202, 'province_id' => 92, 'name' => 'Kab. Manokwari']);
        DB::table('cities')->insert(['id' => 9203, 'province_id' => 92, 'name' => 'Kab. Fak Fak']);
        DB::table('cities')->insert(['id' => 9204, 'province_id' => 92, 'name' => 'Kab. Sorong Selatan']);
        DB::table('cities')->insert(['id' => 9205, 'province_id' => 92, 'name' => 'Kab. Raja Ampat']);
        DB::table('cities')->insert(['id' => 9206, 'province_id' => 92, 'name' => 'Kab. Teluk Bintuni']);
        DB::table('cities')->insert(['id' => 9207, 'province_id' => 92, 'name' => 'Kab. Teluk Wondama']);
        DB::table('cities')->insert(['id' => 9208, 'province_id' => 92, 'name' => 'Kab. Kaimana']);
        DB::table('cities')->insert(['id' => 9209, 'province_id' => 92, 'name' => 'Kab. Tambrauw']);
        DB::table('cities')->insert(['id' => 9210, 'province_id' => 92, 'name' => 'Kab. Maybrat']);
        DB::table('cities')->insert(['id' => 9211, 'province_id' => 92, 'name' => 'Kab. Manokwari Selatan']);
        DB::table('cities')->insert(['id' => 9212, 'province_id' => 92, 'name' => 'Kab. Pegunungan Arfak']);
        DB::table('cities')->insert(['id' => 9271, 'province_id' => 92, 'name' => 'Kota Sorong']);
    }
}
